version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    env_file:
      - docker.env
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    env_file:
      - docker.env
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    

  workers:
  build:
    context: ./worker
    dockerfile: Dockerfile
  volumes:
    - ./:/app
  env_file:
    - docker.env
  depends_on:
    - mysql
  networks:
    - mynetwork


networks:
  mynetwork:
    driver: bridge