version: '3.8'

services:
  backend:
    image: node:14
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    env_file:
      - docker.env
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7
    env_file:
      - docker.env
    ports:
      - "3306:3306"
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge