# Worker Dockerfile

# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install
RUN npm install -g nodemon

# Bundle app source
COPY . .

# FOR DEVELOPMENT
CMD ["npm", "run", "dev-workers"]

# FOR LIVE
# CMD ["npm", "run", "start-workers"]